version: '3.8'
services:
  php:
    image: php:8.1.6RC1-fpm-alpine3.15
    container_name: php
    restart: on-failure
    volumes:
      - ./rainloop:/var/www/html
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: on-failure
    volumes:
      - ./rainloop:/usr/share/nginx/html
      - ./rainloop.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"
